version: '3'
services:

  db:
    image: "postgres"
    logging:
      driver: none
    environment:
      POSTGRES_PASSWORD: '123'
      POSTGRES_USER: postgres
    volumes:
    - db-postgres:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      FLASK_ENV: development

volumes:
  db-postgres:

