version: '3'
services:

  db:
    image: "postgres"
    logging:
      driver: none
    environment:
      POSTGRES_PASSWORD: '123'
      POSTGRES_USER: postgres
    volumes:
    - db-postgres:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "oliveira.stefano@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
      - "8087:80"
    depends_on:
      - db


volumes:
  db-postgres:

